version: '3.6'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=roman
      - POSTGRES_PASSWORD=roman
      - POSTGRES_DB=Todos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: ./
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://roman:roman@postgres:5432/Todos?schema=public
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - PORT=3010
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    volumes:
      - .:/app
volumes:
  postgres-data: